title: Hang Chen's Homepage
page-top-title: Hang Chen
top-section-bg-text: Freely Flying Crows
home-subtitle: Hang Chen
copyright-text: '&copy; Hang Chen 2024-2025. All Rights Reserved. Theme adapted from [Sen Li](https://senli1073.github.io/).'
